---
title: "Getting Started with pandas"
subtitle: ""
author: "Max Arthur Hachemeister"
date: last-modified
toc: true
format: gfm
ipynb-shell-interactivity: all
execute:
    cache: true
---

# Prerequisites
[Link to chapter](https://wesmckinney.com/book/pandas-basics)

Import packages:
```{python}
#| label: setup

# General packages:
import numpy as np
import pandas as pd

# Direct import for convenience:
from pandas import Series, DataFrame
```

# 5.1 Introduction to pandas Data Structures
pandas introduces the *Series* and *DataFrame* object types, which are extensions of of the NumPy *ndarray* we've been working with in the last chapter.

## Series
A Series is a one-dimensional array-like object.
So it contains a sequence of values of the same type, and–this is the pandas addition–an associated array of data labels, called its *index*. Let's take a look:


::: {.callout-note}

I will omit the "Create object..." comment, as I expect you to be able to make sense of the according lines of code without such commentary.

:::

```{python}
obj = pd.Series([4, 7, -5, 3])
obj
```

What you see retured are the index column on the left and the actual values on the right. We can specify this index, but by default it will take integers starting from `0` till `Number of Elements - 1`. You can get either of those columns via the `array` or `index` attribute:

```{python}
obj.array

obj.index
```

You give individual values for the index. They can also be of the string type:

```{python}
obj_2 = pd.Series(
    [4, 7, -5, 3], 
    index = ["d", "b", "a", "c"]
    )
obj_2

obj_2.index
```

One feature panda brings with the string index is that you can select elements, or a range of them, directly by those labels:

```{python}
obj_2["a"]

# Assign the value 6 to the element with the "b" label.
obj_2["d"] = 6

obj_2[["c", "a", "d"]]
```

Each element in a Series preserves its index value (keeps its identity) throughout rearranging operations like filtering, scalar multiplication, or other math functions:

```{python}
# Give me all elements with positive values.
obj_2[obj_2 > 0]

# Multiply all each element by 2.
obj_2 * 2

# Take the exponent of each element.
np.exp(obj_2)
```

A Series is technically an ordered dictionary with the index as key and the data as values. So dictionary functions are also applicable:

```{python}
# Is there an element with key/index "b"?
"b" in obj_2

# Is there an element with key/index "e"?
"e" in obj_2
```

You can even directly transform Python dictionaries into Series:

```{python}
sdata = {
    "Ohio": 35000,
    "Texas": 71000,
    "Oregon": 16000,
    "Utah": 5000
    }

# Cast `sdata` into a series.
obj_3 = pd.Series(sdata)
obj_3
```

And Series have their own `to_dict` method to become dictionaries:

```{python}
obj_3.to_dict()
```

When converting dictionaries to Series the index order of the series follows that of the keys by default. Use the `index` argument to set a different order for the index:

```{python}
# Define the order of index values.
states_order = ["California", "Ohio", "Oregon", "Texas"]

obj_4 = pd.Series(sdata, index = states_order)
obj_4
```

Note, how the index `"California"` got `NaN` (Not a Number) as value, and `"Utah"` didn't make it from the dictionary into the series. `pd.Series()` will respect the index values given by both creating them regardless of their presence in the input object and dropping those elements whose keys weren't called.

To detect "missing", "NA", or "Null" values–or the other way around–use pandas `isna` and `notna` functions:

```{python}
pd.isna(obj_4)

pd.notna(obj_4)
```

Well, Series also have these as methods:

```{python}
obj_4.isna()
```

A relevant feature for arithmetic operations with Series is that the data gets automatically alinged by index values:

```{python}
obj_3

obj_4

obj_3 + obj_4
```

The Series object and its index have a `name` attribute that can be set, and then integrates well with further pandas operations:

```{python}
obj_4.name = "population"

obj_4.index.name = "state"

obj_4
```

::: {.callout-note}

I personally would give `state` its own column, but since we're still talking about series here, this would probably the more efficient way to have that information stored

:::

The index of Series can be, and are, altered in place by an assignmet operation:

```{python}
obj

obj.index = ["Lasagna", "Alfried", "Steward", "Ragna"]
obj
```

## DataFrame

Now, the DataFrame is a rectangular table of data…

::: {.callout-note}

**rectangular** *table* of data seems redundant to me, because a table is usually rectangular by definition, consisting of rows and columns.

Ah well, if I think about it there is a point about separating matrices from tables as they have different arithmetic rules. But that's a pretty specific point, which might confuse at least those–like me–that kinda glossed over, or never really had, matrices in high school.

:::

…and contains an ordererd, named collection of columns (each containing their respective rows). The individual columns can have different value types and still be part of the same DataFrame. Furthemore, both rows and columns have an index. While the columns get their index by default from the keys of the input dictionary, the rows index will be ascending integers starting from 0 by default.

Let's create a dictionary first, and then convert it to a DataFrame:

```{python}
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data)
```

Now, the keys become the index for the colums, and the rows get indexed automatically:

```{python}
frame
```

And then we have methods like `head` and `tail` to get a look at the firs or last five rows, resepectively:

```{python}
frame.head()

frame.tail()
```

You can rearrange the columns by giving the current or source DataFrame as input to `pd.DataFrame` and the desired order as a sequence to the `columns` argument:

```{python}
pd.DataFrame(frame, columns = ["year", "state", "pop"])
```

And just as with Series, DataFrame will respect your sequence and create columns that you gave but might not have existed in the input object, and populate them with `NaN`:

```{python}
pd.DataFrame(frame, columns = ["year", "state", "pop", "lasagna"])
```

Get a single column as a Series either by dictionary call, or as a dot attribute:

```{python}
frame["pop"]

frame.year
```

Rows on the other hand, can be retrieved with special `loc` and `iloc` attributes–which are useful in later contexts, and their difference will be elaborated soon:

```{python}
# Second row
frame.loc[1]

# Third row
frame.iloc[2]
```

So colums are not renamed, but their elements modified, by assigning values to their index:

```{python}
# Scalars are broadcast.
frame["debt"] = 16.5
frame

# Arrays work as well.
frame["debt"] = np.arange(6.)
frame
```

Assigning lists or arrays to DataFrame columns only works when their lengths match. With a series on the other hand, values get aligned to existing indices while all other become `NaN`:

```{python}
#| error: true

val = pd.Series([-1.2, -1.5, -1.7], index = [2, 4, 5])

frame["debt"] = val
frame

frame["debt"] = [1, 1, 2]
```

With the `del` *keyword*, columns can be deleted via a dictionary call. Let's create some columns first:

```{python}
# Create a column named "eastern" where the values are true
# when value of the column "state" of the same row is "Ohio".
frame["eastern"] = frame["state"] == "Ohio"
frame
```

Now let's delete that same column again:

```{python}
del frame["eastern"]

frame.columns
```

You will regularly get dictionaries nested into dictionaries like:

```{python}
populations = {
    "Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
    "Nevada": {2001: 2.4, 2002: 2.9}
}
```

If you pass that to a DataFrame, the outer keys are still the column index, but the inner dictionaries get resolved by setting their keys as row index and the values as values:

```{python}
frame_3 = pd.DataFrame(populations)
frame_3
```

Swap rows and columns with the `T` method–just like with NumPy arrays:

```{python}
frame_3.T
```

Be aware that when setting an index, values from the input that don't match are ommitted:

```{python}
# We're loosing `2000` here.
pd.DataFrame(populations, index = [2001, 2002, 2003])
```

Series nested within dictionaries are resolved indo a DataFrame the same as nested dictionaries:
Series nested within dictionaries are resolved indo a DataFrame the same as nested dictionaries:

```{python}
pdata = {
    # We're getting lists from indexing them out of the `frame_3` object.
    # Assing to the key `Ohio`:
    # From `frame_3`, column `Ohio`, every but the last row.
    "Ohio": frame_3["Ohio"][:-1],
    # Assign the the key `Nevada`:
    # From `frame_3` , column `Nevada`, get the first two rows.
    "Nevada": frame_3["Nevada"][:2],
}

# Make pdata a DataFrame
pd.DataFrame(pdata)
```

As with Series, the DataFrames attributes `index` and `columns` can be set, and will be displayed if so:

```{python}
frame_3.index.name = "year"

frame_3.columns.name = "state"

frame_3
```

This means however, than DataFrame itself does not have a `name` attribute–as opposed to Series.

::: {.callout-note}

Something about the details of the `to_numpy` method

:::

## Index Objects
In pandas, the index are their own objects which can be assinged any series type to set the index values (we did this to some extent above already):

```{python}
obj = pd.Series(np.arange(3), index=["a", "b", "c"])

# Here, we extract the `index`.
index = obj.index

# And see that it is an independent `object` indeed.
index

# For which regular indexing applies.
index[1:]
```

Interesting, yet sensible, these index objects are immutable– their elements cannot be manually altered in place:

```{python}
#| error: true

index[1] = "Lasagna"
```

So the structure/data type of index objects is respected when used in other functions–that's the immutability:

```{python}
# Creating a literal index object.
labels = pd.Index(np.arange(3))
labels

# "Integrating" it into a Series.
obj_2 = pd.Series([1.5, -2.5, 0], index = labels)
obj_2

# See, it's referencing that `label` object.
obj_2.index is labels
```

Now you know.

Values of the index can be queried:

```{python}
frame_3.columns

"Ohio" in frame_3.columns

2003 in frame_3.index
```

And if values occur multiple times, all of them will be returned/selected.


::: {.callout-note}

And a list of useful index methods and properties.

:::

# 5.2 Essential Functionality
## Reindexing
Knowing the above, we can now see how this translates to quite neat functonality with pandas DataFrames and Series. Let's create one to play around with:

```{python}
# Index deliberately in a perculiar order.
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ["d", "b", "a", "c"])
obj
```

The `reindex` method rearranges the data according to the index you give. As shown previously, indexes that are not explicitly called for will be ommitted from the input data, and indexes for which no elements exist in the input data will be created regardless:

```{python}
obj_2 = obj.reindex(["a", "c", "d", "e"])
obj_2
```

Within this method, there is the–wait for it–`method` keyword to address indices for which input data might be missing. For example, giving `ffil` as the argument's value will *forward fill* (repeat) the last value until the index for which a value exists again in the input data:

```{python}
obj_3 = pd.Series(
    ["Alfried", "Lasagna", "Ragna"],
    index = [0, 2, 5]
    )
obj_3

obj_3.reindex(np.arange(7), method = "ffill")
```

And for DataFrame you can address either the index (rows), columns, or both. The index (rows) are the the default target when giving just one sequence:

```{python}
frame = pd.DataFrame(
    np.arange(9).reshape((3, 3)),
    index=["a", "c", "d"],
    columns=["Ohio", "Texas", "California"],
)
frame

frame_2 = frame.reindex(index=["a", "b", "c", "d"])
frame_2
```

To reindex the columns, supply the sequence to the–well–`columns` keyword:

```{python}
states = ["Texas", "Utah", "California"]

frame.reindex(columns = states)
```

A variant of this would be to supply the sequence as the first *positional* argument, and then set the direction with the `axis` keyword:

```{python}
frame.reindex(states, axis = "columns")
```

Might be more clear this way, but whatever you feel like.


::: {.callout-note}

Another table of further arguments and keywords for `reindex`.

:::

Quick mention of the `loc` operator–we already heard of this before, and will again shortly–that also does reindexing but refuses to create elements that did not already exist in the input, so the index sequence has to match the values of the input:

```{python}
#| error: true

frame.loc[
    ["a", "d", "c"],
    ["California", "Texas"],
]

frame.loc[
    ["a", "b", "c"],
    ["California", "Texas"]
]
```

## Dropping Entries from an Axis

We learned above that we can have elements get ommitted from any axis when we leave out the according index value. This might be cumbesome, however, as you'd always have to note *all* of the label values you wanted to keep. The `drop` method will do the trick, by returning the input object with those values dropped that you give:

```{python}
obj = pd.Series(np.arange(5.), index = ["a", "b", "c", "d", "e"])
obj

# By default the row labels (axis 0) are addressed.
new_obj = obj.drop("c")
new_obj

obj.drop(["d", "c"])
```

With DataFrame you have two options to set the addressed label axis for `drop`:

```{python}
data = pd.DataFrame(
    np.arange(16).reshape((4, 4)),
    index = ["Ohio", "Colorado", "Utah", "New York"],
    columns = ["one", "two", "three", "four"],
    )
data
```

So row(index) labels by default:

```{python}
data.drop(index = ["Colorado", "Ohio"])
```

Now for the column labels:

```{python}
# Either with the colums argument.
data.drop(columns = ["two"])

# Or labels sequence as positional
# and then via the axis keyword.
data.drop("two", axis = 1)

# You can also call the axis by its name.
data.drop(["two", "four"], axis = "columns")
```

## Indexing, Selection, and Filtering
Ah yeah, we're coming to the `loc` and `iloc` operators now.
But first, the overall situation for the rationale. Series and DataFrame elements can be indexed, filtered and selected with `[]`, like NumPy Arrays, but you can not only give integers but also the according axis labels. Here are some examples:

```{python}
obj = pd.Series(np.arange(4.), index = ["a", "b", "c", "d"])
obj

# Get row "b".
obj["b"]

# Get rows 3 to 4.
obj[2:4]

# Get rows "a", "b", and "d" in that exact order.
obj[["a", "b", "d"]]

# Get all rows for which the value is less than 2.
obj[obj < 2]

```


::: {.callout-note}

Seems like selecting with integers, either single or list, gives an error, but ranges still work.

So these calls don't work:

```{python}
#| eval: false

# Get rows 3 and 4.
obj[[2, 3]]

# Get the second row.
obj[1]
```

Ah yea, you can read it in the error report:

> 957 # Note: GH#50617 in 3.0 we changed int key to always be treated as
> 958 # a label, matching DataFrame behavior.

:::

So you can only use integers in indexing when the axis labels are integers, too:

```{python}
obj_2  = pd.Series(np.arange(6.))
obj_2

obj_2[1]

obj_2[[2, 4]]

obj_2[[0, 5, 1]]

obj_2[obj_2 < 2]
```

However, you can use `iloc` to ignore labels and select by "position", solving the above error:

```{python}
obj
obj.iloc[1]

obj.iloc[[2, 3]]
```

And the `loc` indexer only works with labels and throws an error when encountering integer axis values. But, as seen above, the default behaviour of the regular index operator will let you know when you mix it up in both cases.

Furthemore, when you assing values to an index call, they will be assigned to the actual values insted of the axis label:

```{python}
obj_3 = pd.Series(
    [1, 2, 3],
    index = ["a", "b", "c"]
)
obj_3

obj_3.loc["b":"c"] = 5
obj_3
```

For DataFrame, the default axis for indexing is across the columns (1):

```{python}
data = pd.DataFrame(
    np.arange(16).reshape((4, 4)),
    index = ["Ohio", "Colorado", "Utah", "New York"],
    columns = ["one", "two", "three", "four"]
)
data

data["two"]

data[["three", "one"]]
```

Now, there are some further idiosycracies:

```{python}
# Slicing addresses the row axis (0),
data[:2]

# But boolean filtering only from the second layer.
# Well, not really, but check the later example.
data[data["three"] > 5]

# In the first layer you get `NaN`s.
data[data > 5]

# And the naked operation assings boolean values directly.
data < 5
```

So with boolean filtering you can assing new values to the `True`s of the filter call. For example, assing the value 0 to *every* datapoint that is less than 5 in `data`:

```{python}
data[data < 5] = 0
data
```

### Selection on DataFrame with Loc and Iloc

`loc` and `iloc` apply to DataFrame like for Series plus the addressing of axis. Let's get a single row by label:

```{python}
data

data.loc["Colorado"]
```


::: {.callout-caution}

Typo
>  To select multiple **roles** {rows?}, creating a new DataFrame, pass a sequence of labels:

:::

Passing a list of labels gives you a new DataFrame:

```{python}
data.loc[["Colorado", "New York"]]
```

You can also select certain rows of those selected columns by passing another list after a comma:

```{python}
data.loc["Colorado", ["three", "four"]]

# Behaves differently if you pass the row selector as a list.
data.loc[["Colorado"], ["three", "four"]]
```

Same syntax works for integer selection with `iloc`:

```{python}
# Get third row
data.iloc[2]

# Get rows three and two, in that exact order.
data.iloc[[2, 1]]

# Get third row of columns four, one and two, in that exact order
data.iloc[2, [3, 0, 1]]

# Get second and third row of columns four, one and two in that exact order.
data.iloc[[1, 2], [3, 0, 1]]
```

Ah wild, you can even slice with labels and some boolean arrays:

```{python}
# All rows up to (inclusively this time) "Utah" of column two.
data.loc[:"Utah", "two"]

# All rows of all columns up to (exclusively) row four
# and from that only the rows with values larger than 5 in column three.
data.iloc[:, :3][data.three > 5]
```

Boolean arrays work with `loc` and `iloc` alike:

```{python}
# Get those rows with values larger or equal to 2 in column three.
data.loc[data.three >= 2]
```

#### Integer Indexing Pifalls

Indexing with integers has some perticular behavior, which probably grew out of preventing hard to detect user errors. For example, you will get an error with the following code:

```{python}
#| error: true

ser = pd.Series(np.arange(3.))
ser

ser[-1]
```

As the index of the series are integers, this indexing call can refer to either positional or label-based indexing, and pandas does not want to guess.

If we were to ask the same thing from an non-integer index there is no ambiguity and the code will succeed:

```{python}
#| error: true

ser_2 = pd.Series(
    np.arange(3.),
    index = ["a", "b", "c"]
    )

ser_2[-1]
```


::: {.callout-note}

Ah, well, It seems this is not the case anymore. So pandas will throw an error in both cases, and you are sternly proposed to use `loc` and `iloc` for the above operations, to be really precise about the type of indexing you want–rightfully so.

:::

So, to be precise about what you want, use `loc` and `iloc`:

```{python}
# Select by position.
ser.iloc[-1]

# Select by label.
ser.loc[2]
```

For your convenience however, slicing with integers will allways be positional:

```{python}
# Give me the first rows.
ser_2[:2]
```

The jist is: Use `loc` and `iloc` whenever applicable.

#### Pittfalls with Chained Indexing

We've gotten to know the flexible selecting with `loc` and `iloc` by now. The next logical step is often to assign new values to these selection, which is another thing to wrap your head around first.

Whole rows and columns are relatively straight forward:

```{python}
# Assign all rows of column "one" the value 1.
data.loc[:, "one"] = 1
data

# Assign all columns of the third row the value 5.
data.iloc[2] = 5
data

# Assign all columns of the row where
# the value in column "four" is larger than 5 the value 3.
data.loc[data["four"] > 5] = 3
data
```

The thing to keep in your mind when selecting a combination of rows and columns is that when a call returns a subset, it will fail assing any values given as it does not refer to the original object anymore:

```{python}
#| error: true

# This is subsetting/creating a new Series
data.loc[data.three == 5]["three"] = 6
```

You even get a verbose error, explaining to you you that you should use the row and column indexers in the same `loc` or `iloc` call, instead of chaining them:

```{python}
data.loc[data.three == 5, "three"] = 123
data
```

## Arithmetic and Data Alignment
